name: fake_store_api_package
description: "Paquete Flutter/Dart para interactuar fácilmente con la Fake Store API. Incluye métodos CRUD y procesamiento de datos."
version: 0.0.5
homepage: https://github.com/bruno8311/fake_store_api_package

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  http: ^1.1.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
